services:
  base:
    image: pinocchio_ros_cpp:${ROS_DISTRO}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Mount files
    volumes:
      - ./pinocchio_ros_example/:/workspace/src/pinocchio_ros_example/
